food: {
    titles: [
        "This {topic} recipe will literally make you drool 🤤",
        "Secret restaurant-style {topic} recipe revealed! 🤫🍲",
        "Stop buying {topic}, make it at home easily like this! 👨‍🍳",
        "I tried making the viral {topic} and OMG... 😱",
        "The only {topic} recipe you will ever need in your life 🥘",
        "Rating this homemade {topic} a 100/10 💯",
        "Quick and easy {topic} recipe for lazy days ⏳",
        "POV: You just found the perfect {topic} recipe 👩‍🍳✨",
        "My family asks for this {topic} every single weekend! 👨‍👩‍👧‍👦",
        "If you have 10 minutes, make this viral {topic} ⏱️🔥",
        "Better than takeout! This {topic} is a game changer 🥡",
        "The secret ingredient for the best {topic} ever 🤫✨",
        "Husband approved! This {topic} is his new favorite 💖",
        "Stop scrolling! This {topic} hack is actually genius 🤯",
        "Why is nobody talking about this {topic} trick? 🧐",
        "My most requested {topic} recipe is finally here! 📢",
        "Level up your {topic} game with this one simple step 📈",
        "Cheap vs Expensive {topic}: Homemade version wins! 🏆",
        "I can’t stop eating this {topic}, it’s too good! 🤤🔥",
        "No oven? No problem! Try this {topic} instead 🚫🔥",
        "Everything you know about {topic} is a lie... try this! ❌",
        "The crunch on this {topic} is absolute perfection 🔊👂",
        "Is this the best {topic} in the world? Let’s find out! 🌍",
        "Master the art of {topic} in under 60 seconds 🎨",
        "Your guests will think you ordered this {topic} from a 5-star hotel 🏨",
        "10-minute {topic} for when you're hungry and lazy 🥱",
        "The most satisfying {topic} ASMR you’ll see today 👂✨",
        "Healthy {topic} that actually tastes like a cheat meal! 🥗",
        "I made {topic} for the first time and I'm shocked! 😲",
        "This {topic} is taking over the internet right now! 🌐",
        "Authentic {topic} just like grandma used to make 👵❤️",
        "One-pot {topic} for people who hate doing dishes 🧼",
        "This is your sign to go make some {topic} right now! ✨",
        "If {topic} was a love language, this would be it 💖🥘",
        "Secret street food style {topic} at home! 🛣️🔥",
        "Don't make {topic} until you watch this video! 🛑",
        "Softest and juiciest {topic} you will ever taste ☁️🥩",
        "Wait for the result... this {topic} is insane! 😱✨",
        "Transform your boring {topic} into something gourmet 💎",
        "My kids literally begged for more {topic}! 👶🍲",
        "Forget the old way, this is the new {topic} trend 📉",
        "How to make {topic} like a professional chef 👨‍🍳🔥",
        "The ultimate comfort food: {topic} Edition ☁️",
        "Is this viral {topic} worth the hype? 🤨",
        "Budget friendly {topic} that tastes like a million bucks 💵",
        "I added a secret spice to this {topic} and WOW 🌶️😲",
        "Craving {topic}? This is the easiest way to make it! 🤤",
        "Making {topic} for the person I love ❤️🍲",
        "3 tips to make your {topic} perfectly every time 💡",
        "Finally sharing my secret {topic} sauce recipe! 🍯"
    ],
    tags: [
        "foodie", "tiktokfood", "recipe", "cooking", "foodtiktok", "easyrecipe", 
        "delicious", "foodlover", "desifood", "kitchen", "asmrcooking", "streetfood", 
        "homecooking", "lunchideas", "dinnerwithme", "foodtok", "quickrecipes", 
        "pakistanifood", "indianfood", "healthyrecipes", "easycooking", "chefmode", 
        "halalfood", "foodhacks", "viralfood"
    ]
}
